# Generated by Django 2.2 on 2020-05-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank='True', null='True'),
            preserve_default='True',
        ),
    ]
