# Generated by Django 2.2 on 2020-05-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This ia a tezt description bwbss cshkcbdf eueoef efefsksjdnf ffjffnlfnfi fjfffofff fjffoef efheuofemef fjfuofefmef'),
            preserve_default=False,
        ),
    ]
